version: '3.9'

services:
  mongodb:
    image: mongo:latest
    container_name: my_mongo
    ports:
      - "27017:27017"
    networks:
      - my_network
    volumes:
      - ../mongo_docker/data:/data/db:rw
  api:
    image: pauldechorgnat/cdc_demo_api:latest
    container_name: my_api
    ports:
    - "8000:8000"
    networks:
      - my_network
    environment:
      - ENVIRONMENT=docker-compose
    depends_on:
      - mongodb
  prometheus:
    image: prom/prometheus:latest
    container_name: my_prometheus
    ports:
    - "9090:9090"
    networks:
      - my_network
    volumes:
      - ../prometheus_docker/prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - api
  dashboard:
    image: grafana/grafana:latest
    container_name: my_dashboard
    ports:
    - "3000:3000"
    networks:
      - my_network

networks:
  my_network:
