name: ci

on:
  push:
    branches:
      - "master"

jobs:
  docker_build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build Docker Image
        run: sh api_docker/build_api_image.sh

      - name: Push Docker Image
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: pauldechorgnat/cdc_demo_api:latest
